data: !dict '{{ "{" }}
  {% for x in range(1, _.maxleadtime.int + 1) %}
  {{ _.dir }}/{{ (cycle + _.delta * x).strftime(_.fmt.gfs) }}: {{ _.bcs.prefix }}{{ "%03d" % (x + _.cycles.below.offset) }},
  {% endfor %}
  {{ _.dir }}/{{ (cycle + _.cycles.above.delta).strftime(_.fmt.gfs) }}: {{ _.bcs.prefix }}{{ "%03d" % _.cycles.above.offset }},
  {{ _.dir }}/{{ _.cycles.prev.cycle.strftime(_.fmt.hrrr) }}_surface_f01.grib2: {{ _.ics.prefix.prev }}.wrfsfcf01.grib2,
  {{ _.dir }}/{{ cycle.strftime(_.fmt.hrrr) }}_pressure.grib2: {{ _.ics.prefix.this }}.wrfprsf00.grib2,
  {{ _.dir }}/{{ cycle.strftime(_.fmt.hrrr) }}_surface.grib2: {{ _.ics.prefix.this }}.wrfsfcf00.grib2,
  {{ "}" }}'
_:
  urlbase:
    bcs: https://noaa-gfs-bdp-pds.s3.amazonaws.com
    ics: https://noaa-hrrr-bdp-pds.s3.amazonaws.com
  bcs:
    prefix: '{{ _.urlbase.bcs }}/gfs.{{ _.cycles.below.yyyymmdd }}/{{ _.cycles.below.hh }}/atmos/gfs.t{{ _.cycles.below.hh }}z.pgrb2.0p25.f'
  cycles:
    above:
      delta: !timedelta '{{ _.cycles.above.synoptic - cycle }}'
      hours_to_next_synoptic: !timedelta '{{ (6 - (_.cycles.above.maxvalidtime.hour % 6)) % 6 }}'
      maxvalidtime: !datetime '{{ cycle + _.maxleadtime.timedelta }}'
      offset: !int '{{ (_.cycles.above.synoptic - _.cycles.below.synoptic).total_seconds() / 3600 }}'
      synoptic: !datetime '{{ _.cycles.above.maxvalidtime + _.cycles.above.hours_to_next_synoptic }}'
    below:
      delta: !timedelta '{{ _.cycles.below.offset }}'
      hh: '{{ _.cycles.below.synoptic.strftime("%H") }}'
      offset: !int '{{ cycle.timestamp() % (3600 * 6) / 3600 }}'
      synoptic: !datetime '{{ cycle - _.cycles.below.delta }}'
      yyyymmdd: '{{ _.cycles.below.synoptic.strftime("%Y%m%d") }}'
    prev:
      cycle: !datetime '{{ cycle - _.delta }}'
      hh: '{{ _.cycles.prev.cycle.strftime("%H") }}'
      yyyymmdd: '{{ _.cycles.prev.cycle.strftime("%Y%m%d") }}'
    this:
      hh: '{{ cycle.strftime("%H") }}'
      yyyymmdd: '{{ cycle.strftime("%Y%m%d") }}'
  delta: !timedelta 01:00:00
  dir: '{{ _.cycles.this.yyyymmdd }}/{{ _.cycles.this.hh }}'
  fmt:
    gfs: gfs_%Y%m%d_%H.grib2
    hrrr: hrrr_%Y%m%d_%H
  ics:
    prefix:
      prev: '{{ _.urlbase.ics }}/hrrr.{{ _.cycles.prev.yyyymmdd }}/conus/hrrr.t{{ _.cycles.prev.hh }}z'
      this: '{{ _.urlbase.ics }}/hrrr.{{ _.cycles.this.yyyymmdd }}/conus/hrrr.t{{ _.cycles.this.hh }}z'
  maxleadtime:
    int: !int '{{ leadtime.total_seconds() / 3600 }}'
    timedelta: !timedelta '{{ _.maxleadtime.int }}'
