#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<EOF >&2
Usage: $(basename "$0") --init VALUE --length VALUE

Settings:
  --init   Forecast init time as YYYY-MM-DDTHH
  --length Forecast length in hours
EOF
  exit 1
}

# Parse args:

while [[ $# -gt 0 ]]; do
  case "$1" in
    --init)   init="$2"   ;;
    --length) length="$2" ;;
    *)        usage       ;;
  esac
  shift 2
done

# Check args:

for var in init length; do
  test -z "${!var:-}" && usage || true
done

# Get data:

cmd=(
  uw fs copy
  --config config.yaml
  --key-path data
  --cycle $init
  --leadtime $length
  --threads 8
  --report
)
(set -x && ${cmd[*]}) | jq -e 'select(."not-ready" == [])' >/dev/null
